from pathlib import Path
import re

p = Path('index.html')
s = p.read_text(encoding='utf-8')
marker = '<!-- NEXTPLAN_PHASE_C_V1 -->'

nav_review = '''    <button class="nav-btn" data-view="review"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><path d="M4 5h16v14H4z"/><path d="M8 9h8M8 13h5M8 17h7"/></svg>Weekly Review</button>'''
review_section = '''  <section class="view" id="view-review"><div class="view-title"><h2>Weekly Review</h2><p>过去 7 天的推进、停滞、等待和未来 14 天的时间压力。</p></div><div class="analytics-grid" id="reviewMetrics"><div class="card analytics-card"><h4>Movement</h4><div class="metric-big" id="reviewEvents7">0</div><div class="metric-label">state changes in the last 7 days</div></div><div class="card analytics-card"><h4>Completions</h4><div class="metric-big" id="reviewCompletions">0</div><div class="metric-label">confirmed completion events</div></div><div class="card analytics-card"><h4>Waiting / Blocked</h4><div class="metric-big" id="reviewWaiting">0</div><div class="metric-label">projects requiring review, not immediate execution</div></div><div class="card analytics-card"><h4>Next 14 Days</h4><div class="metric-big" id="reviewUpcoming">0</div><div class="metric-label">confirmed calendar items and deadlines</div></div></div><div style="height:14px"></div><div class="analytics-grid"><div class="card analytics-card"><h4>Attention</h4><div id="reviewAttention" class="review-list"></div></div><div class="card analytics-card"><h4>Completed This Week</h4><div id="reviewCompleted" class="review-list"></div></div><div class="card analytics-card"><h4>Upcoming</h4><div id="reviewSchedule" class="review-list"></div></div><div class="card analytics-card"><h4>Review Prompt</h4><div id="reviewPrompt" class="review-list"></div></div></div></section>'''
analytics_section = '''  <section class="view" id="view-analytics"><div class="view-title"><h2>Analytics</h2><p>不是 KPI，而是回答“系统有没有向前走，以及哪里开始失去控制”。</p></div><div class="analytics-grid"><div class="card analytics-card"><h4>Progress by Area</h4><div id="areaProgress"></div></div><div class="card analytics-card"><h4>Movement</h4><div class="metric-big" id="events7">0</div><div class="metric-label">state changes · 7 days</div><div style="height:14px"></div><div class="metric-big" id="events30">0</div><div class="metric-label">state changes · 30 days</div><div style="height:14px"></div><div class="metric-big" id="completion30">0</div><div class="metric-label">completion events · 30 days</div></div><div class="card analytics-card"><h4>Execution Health</h4><div class="metric-big" id="nextActionCoverage">0%</div><div class="metric-label">active projects with a next action</div><div style="height:14px"></div><div class="metric-big" id="waitingCountAnalytics">0</div><div class="metric-label">waiting projects</div></div><div class="card analytics-card"><h4>Milestones</h4><div class="metric-big" id="milestoneDone">0</div><div class="metric-label" id="milestoneLabel">completed milestones</div></div><div class="card analytics-card"><h4>Time Pressure</h4><div class="metric-big" id="overdueCount">0</div><div class="metric-label">overdue deadlines</div><div style="height:14px"></div><div class="metric-big" id="upcoming14Count">0</div><div class="metric-label">items in the next 14 days</div></div><div class="card analytics-card"><h4>Knowledge Base</h4><div class="metric-big" id="knowledgeCount">0</div><div class="metric-label" id="knowledgeLabel">notes + resources</div></div><div class="card analytics-card"><h4>Stale Active Work</h4><div id="analyticsStale" class="review-list"></div></div><div class="card analytics-card"><h4>System</h4><div class="list-sub" id="analyticsUpdated">Last updated: —</div><div class="list-sub" style="margin-top:8px">Conversation-controlled central state</div><div class="list-sub" style="margin-top:8px">Waiting / blocked items excluded from Next Action</div></div></div></section>'''

css = '''
/* NEXTPLAN PHASE C */
.review-list{display:grid;gap:8px;margin-top:8px}.review-item{padding:9px 10px;border-radius:11px;background:var(--panel-soft);font-size:12px;line-height:1.45}.review-item b{display:block;color:var(--text);font-size:12px;margin-bottom:2px}.review-muted{color:var(--muted)}.knowledge-meta{display:flex;gap:6px;flex-wrap:wrap;margin-top:8px}.knowledge-chip{font-size:10px;border-radius:999px;background:var(--chip);color:var(--muted);padding:3px 7px}.resource-link{color:var(--blue);text-decoration:none;word-break:break-all}.resource-link:hover{text-decoration:underline}.search-result[data-palette-view]{cursor:pointer}.search-result[data-palette-view]:hover{background:var(--panel-soft)}.search-command{color:var(--blue);font-weight:700}.search-help{font-size:11px;color:var(--muted);padding:8px 4px 4px}
'''

helpers = r'''function projectById(id){return (state.projects||[]).find(p=>String(p.id)===String(id))||null}
function stateEventDate(raw){const d=new Date(raw);return Number.isNaN(d.getTime())?null:d}
function completionEvent(e){const t=String(e.type||''),s=String(e.summary||'').toLowerCase();return t==='task_completed'||t==='milestone_completed'||(t==='milestone_status_changed'&&s.includes('completed'))}
function lastActivityMap(){const out={};(state.events||[]).forEach(e=>{const d=stateEventDate(e.at),pid=String(e.project_id||'');if(!d||!pid)return;if(!out[pid]||d>out[pid])out[pid]=d});return out}
function weeklyReviewData(){const now=new Date(),cut=new Date(now.getTime()-7*86400000),events=(state.events||[]).filter(e=>{const d=stateEventDate(e.at);return d&&d>=cut}),completed=events.filter(completionEvent),ps=state.projects||[],waiting=ps.filter(p=>p.status==='waiting'),blocked=ps.filter(p=>p.status==='blocked'),active=ps.filter(p=>p.status==='active'),activity=lastActivityMap(),stale=[],missing=[];active.forEach(p=>{const last=activity[String(p.id)],age=last?Math.floor((now-last)/86400000):null;if(age===null||age>=7)stale.push({p,age});const activeMs=(p.milestones||[]).filter(m=>m.status==='active');if(!String(p.next_action||'').trim()&&!activeMs.length)missing.push(p)});const entries=calendarEntries(),today=startOfToday(),upcoming=entries.filter(x=>{const d=daysDiff(x.date);return d>=0&&d<=14}),overdue=confirmedDeadlines().filter(x=>daysDiff(x.date)<0);return{events,completed,waiting,blocked,active,stale,missing,upcoming,overdue}}
function reviewItem(title,sub=''){return `<div class="review-item"><b>${esc(title)}</b>${sub?`<span class="review-muted">${esc(sub)}</span>`:''}</div>`}
function renderWeeklyReview(){const r=weeklyReviewData();$('reviewEvents7').textContent=r.events.length;$('reviewCompletions').textContent=r.completed.length;$('reviewWaiting').textContent=r.waiting.length+r.blocked.length;$('reviewUpcoming').textContent=r.upcoming.length;const attention=[];if(r.overdue.length)attention.push(reviewItem(`${r.overdue.length} overdue deadline(s)`,'Resolve or reschedule confirmed deadlines.'));if(r.blocked.length)attention.push(reviewItem(`${r.blocked.length} blocked project(s)`,r.blocked.map(p=>p.name).join(' · ')));if(r.stale.length)attention.push(reviewItem(`${r.stale.length} stale active project(s)`,r.stale.slice(0,4).map(x=>x.p.name+(x.age==null?' · no activity timestamp':` · ${x.age}d`)).join(' | ')));if(r.missing.length)attention.push(reviewItem(`${r.missing.length} project(s) missing a next action`,r.missing.map(p=>p.name).join(' · ')));$('reviewAttention').innerHTML=attention.length?attention.join(''):reviewItem('No structural warning detected','Continue the highest-scoring current action.');$('reviewCompleted').innerHTML=r.completed.length?r.completed.slice(0,6).map(e=>reviewItem(e.summary||'Completed',formatUpdated(e.at))).join(''):reviewItem('No completion recorded this week','Progress can still exist in active work; only confirmed completions appear here.');$('reviewSchedule').innerHTML=r.upcoming.length?r.upcoming.slice(0,7).map(x=>reviewItem((x.time?x.time+' ':'')+x.title,`${localISO(x.date)} · ${x.type==='deadline'?'Deadline':x.kind||'Event'}`)).join(''):reviewItem('No confirmed item in the next 14 days');const prompts=[];if(r.overdue.length)prompts.push('Resolve overdue deadlines before adding new commitments.');if(r.stale.length)prompts.push('Decide whether stale active projects should move, wait, or be paused.');if(r.waiting.length)prompts.push('Check whether any waiting item now has new information.');if(!prompts.length)prompts.push('Review the top current action and protect time for it.');$('reviewPrompt').innerHTML=prompts.map(x=>reviewItem(x)).join('')}
function analyticsData(){const now=Date.now(),ps=state.projects||[],events=state.events||[],e7=events.filter(e=>{const t=new Date(e.at).getTime();return Number.isFinite(t)&&t>=now-7*86400000}).length,e30=events.filter(e=>{const t=new Date(e.at).getTime();return Number.isFinite(t)&&t>=now-30*86400000}),c30=e30.filter(completionEvent).length,active=ps.filter(p=>p.status==='active'),coverage=active.length?Math.round(100*active.filter(p=>String(p.next_action||'').trim()).length/active.length):100,allMs=ps.flatMap(p=>p.milestones||[]),today=startOfToday(),overdue=confirmedDeadlines().filter(x=>x.date<today).length,up14=calendarEntries().filter(x=>{const d=daysDiff(x.date);return d>=0&&d<=14}).length,activity=lastActivityMap(),stale=active.map(p=>{const d=activity[String(p.id)];return{p,age:d?Math.floor((Date.now()-d)/86400000):null}}).filter(x=>x.age===null||x.age>=7).sort((a,b)=>(b.age??9999)-(a.age??9999));return{e7,e30:e30.length,c30,coverage,allMs,overdue,up14,stale}}
function searchIndex(){const rows=[];const add=(kind,title,sub,view,extra={})=>rows.push({kind,title:String(title||''),sub:String(sub||''),view,...extra});(state.projects||[]).forEach(p=>{add('Project',p.name,p.next_action||'','projects',{status:p.status,area:p.category,project:p.name});(p.milestones||[]).forEach(m=>add('Task',m.name,p.name+' · '+statusLabel(m.status),'tasks',{status:m.status,area:p.category,project:p.name}))});(state.notes||[]).forEach(n=>add('Note',n.title||'Note',n.body||n.text||'','notes',{area:n.category||'',project:projectById(n.project_id)?.name||''}));(state.resources||[]).forEach(r=>add('Resource',r.title||r.name||'Resource',r.description||r.location||'','resources',{area:r.type||'',project:projectById(r.project_id)?.name||''}));confirmedDeadlines().forEach(d=>add('Deadline',d.title,localISO(d.date)+(d.time?' · '+d.time:''),'calendar',{area:d.category||'',project:projectById(d.project_id)?.name||''}));(state.calendar_events||[]).forEach(e=>add('Calendar',e.title||e.name||'Event',(e.date||'')+(e.time?' · '+e.time:'')+' · '+(e.kind||'event'),'calendar',{area:e.category||'',project:projectById(e.project_id)?.name||''}));(state.events||[]).slice(0,100).forEach(e=>add('History',e.summary||e.type||'Event',e.at||'','review',{project:projectById(e.project_id)?.name||''}));return rows}
function parseSearchQuery(raw){const filters={},terms=[];String(raw||'').trim().split(/\s+/).filter(Boolean).forEach(t=>{const i=t.indexOf(':');if(i>0&&['kind','type','status','area','project'].includes(t.slice(0,i).toLowerCase()))filters[t.slice(0,i).toLowerCase()]=t.slice(i+1).toLowerCase();else terms.push(t.toLowerCase())});return{terms,filters}}
const paletteCommands=[['>home','Home','home'],['>projects','Projects','projects'],['>tasks','Tasks','tasks'],['>calendar','Calendar','calendar'],['>review','Weekly Review','review'],['>notes','Notes','notes'],['>resources','Resources','resources'],['>analytics','Analytics','analytics']];'''

render_notes = r'''function renderNotes(){const notes=state.notes||[];$('notesGrid').innerHTML=notes.length?notes.map(n=>{const p=projectById(n.project_id),tags=Array.isArray(n.tags)?n.tags:[],meta=[n.category||'Note',p?.name,n.updated_at?`Updated ${formatUpdated(n.updated_at)}`:n.at?formatUpdated(n.at):''].filter(Boolean).join(' · ');return `<div class="card note-card"><div class="note-title">${esc(n.title||'Note')}</div><div class="note-body">${esc(n.body||n.text||'')}</div><div class="note-meta">${esc(meta)}</div>${tags.length?`<div class="knowledge-meta">${tags.map(t=>`<span class="knowledge-chip">${esc(t)}</span>`).join('')}</div>`:''}</div>`}).join(''):`<div class="card empty-state" style="grid-column:1/-1"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7"><path d="M5 3h14v18H5z"/><path d="M8 8h8M8 12h8"/></svg><b>还没有 Notes</b>明确说“把这个想法记下来作为笔记”，NextPlan 会保存为信息，而不是任务。</div>`}'''
render_resources = r'''function renderResources(){const rs=state.resources||[];$('resourcesGrid').innerHTML=rs.length?rs.map(r=>{const p=projectById(r.project_id),tags=Array.isArray(r.tags)?r.tags:[],loc=String(r.location||''),safe=/^https?:\/\//i.test(loc),meta=[r.type||'resource',p?.name,r.updated_at?`Updated ${formatUpdated(r.updated_at)}`:r.at?formatUpdated(r.at):''].filter(Boolean).join(' · ');return `<div class="card resource-card"><div class="resource-icon"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><path d="M7 3h8l4 4v14H7z"/><path d="M15 3v5h5"/></svg></div><div><div class="resource-title">${esc(r.title||r.name||'Resource')}</div><div class="resource-sub">${esc(r.description||'')}</div><div class="note-meta" style="margin-top:5px">${esc(meta)}</div><div style="margin-top:5px">${safe?`<a class="resource-link" href="${esc(loc)}" target="_blank" rel="noopener noreferrer">${esc(loc)}</a>`:`<span class="review-muted">${esc(loc)}</span>`}</div>${tags.length?`<div class="knowledge-meta">${tags.map(t=>`<span class="knowledge-chip">${esc(t)}</span>`).join('')}</div>`:''}</div></div>`}).join(''):`<div class="card empty-state" style="grid-column:1/-1"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7"><path d="M8.5 13.5 6 16a4 4 0 1 0 5.7 5.6l3-3"/><path d="m15.5 10.5 2.5-2.5a4 4 0 1 0-5.7-5.6l-3 3"/><path d="m9 15 6-6"/></svg><b>还没有资源索引</b>明确说“把这个链接保存为资源”，NextPlan 会保存安全指针，不复制敏感文件内容。</div>`}'''
render_analytics = r'''function renderAnalytics(){const ps=state.projects||[],cats=[...new Set(ps.map(p=>p.category))],a=analyticsData();$('areaProgress').innerHTML=cats.map(c=>{const arr=ps.filter(p=>p.category===c),avg=arr.length?Math.round(arr.reduce((s,p)=>s+projectPct(p),0)/arr.length):0;return `<div class="area-row"><span>${esc(c)}</span><div class="area-track"><span style="width:${avg}%"></span></div><b>${avg}%</b></div>`}).join('');$('events7').textContent=a.e7;$('events30').textContent=a.e30;$('completion30').textContent=a.c30;$('nextActionCoverage').textContent=a.coverage+'%';$('waitingCountAnalytics').textContent=ps.filter(p=>p.status==='waiting').length;const done=a.allMs.filter(m=>m.status==='completed'||m.status==='done').length;$('milestoneDone').textContent=done;$('milestoneLabel').textContent=`completed of ${a.allMs.length} tracked milestones`;$('overdueCount').textContent=a.overdue;$('upcoming14Count').textContent=a.up14;const knowledge=(state.notes||[]).length+(state.resources||[]).length;$('knowledgeCount').textContent=knowledge;$('knowledgeLabel').textContent=`${(state.notes||[]).length} notes + ${(state.resources||[]).length} resources`;$('analyticsStale').innerHTML=a.stale.length?a.stale.slice(0,6).map(x=>reviewItem(x.p.name,x.age==null?'No activity timestamp':`${x.age} days since recorded activity`)).join(''):reviewItem('No active project is stale for 7+ days');$('analyticsUpdated').textContent='Last updated: '+formatUpdated(state.system?.last_updated)}'''
render_search = r'''function renderSearch(q){const raw=String(q||'').trim();if(raw.startsWith('>')){const needle=raw.toLowerCase();const cmds=paletteCommands.filter(c=>c[0].startsWith(needle)||c[1].toLowerCase().includes(needle.slice(1)));$('searchResults').innerHTML=cmds.length?`<div class="search-help">Commands</div>`+cmds.map(c=>`<div class="search-result" data-palette-view="${c[2]}"><span class="search-kind search-command">${esc(c[0])}</span><div><b>${esc(c[1])}</b><p>Open ${esc(c[1])}</p></div></div>`).join(''):`<div class="empty-state"><b>No command</b>Try &gt;review, &gt;calendar or &gt;analytics.</div>`;return}const {terms,filters}=parseSearchQuery(raw),rows=searchIndex().filter(r=>{const hay=[r.kind,r.title,r.sub,r.status||'',r.area||'',r.project||''].join(' ').toLowerCase();if(terms.some(t=>!hay.includes(t)))return false;if(filters.kind&&!r.kind.toLowerCase().includes(filters.kind))return false;if(filters.type&&!r.kind.toLowerCase().includes(filters.type))return false;if(filters.status&&String(r.status||'').toLowerCase()!==filters.status)return false;if(filters.area&&!String(r.area||'').toLowerCase().includes(filters.area))return false;if(filters.project&&!String(r.project||'').toLowerCase().includes(filters.project))return false;return true});$('searchResults').innerHTML=(raw?'<div class="search-help">Search projects, tasks, notes, resources, calendar and history · filters: kind:, status:, area:, project:</div>':'<div class="search-help">Type to search everything, or use &gt;review / &gt;calendar / &gt;analytics.</div>')+(rows.length?rows.slice(0,40).map(r=>`<div class="search-result" data-palette-view="${r.view}"><span class="search-kind">${esc(r.kind)}</span><div><b>${esc(r.title)}</b><p>${esc(r.sub)}</p></div></div>`).join(''):`<div class="empty-state"><b>No results</b>Try another keyword or remove a filter.</div>`)}'''

if marker not in s:
    s = s.replace('<!-- NEXTPLAN_PHASE_B_V1 -->', '<!-- NEXTPLAN_PHASE_B_V1 -->\n'+marker, 1)
    if nav_review not in s:
        anchor = '    <button class="nav-btn" data-view="notes">'
        i = s.find(anchor)
        if i < 0: raise SystemExit('Notes nav anchor missing')
        s = s[:i] + nav_review + '\n' + s[i:]
    if 'id="view-review"' not in s:
        anchor = '  <section class="view" id="view-notes">'
        i = s.find(anchor)
        if i < 0: raise SystemExit('Notes section anchor missing')
        s = s[:i] + review_section + '\n' + s[i:]
    s, n = re.subn(r'  <section class="view" id="view-analytics">.*?</section>', analytics_section, s, count=1, flags=re.S)
    if n != 1: raise SystemExit('Analytics section replacement failed')
    s = s.replace('</style>', css+'\n</style>', 1)
    anchor = 'function renderNotes(){'
    i = s.find(anchor)
    if i < 0: raise SystemExit('renderNotes anchor missing')
    s = s[:i] + helpers + '\n' + s[i:]
    replacements = {
        r'^function renderNotes\(\).*?$': render_notes,
        r'^function renderResources\(\).*?$': render_resources,
        r'^function renderAnalytics\(\).*?$': render_analytics,
        r'function renderSearch\(q\).*?$': render_search,
    }
    for pat, rep in replacements.items():
        s, n = re.subn(pat, rep, s, count=1, flags=re.M)
        if n != 1: raise SystemExit('Function replacement failed: '+pat)
    old = "function renderAll(){renderGreeting();renderHome();renderProjects();renderTasks();renderCalendar(calendarCursor,'calGrid','calTitle',false);renderNotes();renderResources();renderAnalytics();renderMiniSidebar()}"
    new = "function renderAll(){renderGreeting();renderHome();renderProjects();renderTasks();renderCalendar(calendarCursor,'calGrid','calTitle',false);renderWeeklyReview();renderNotes();renderResources();renderAnalytics();renderMiniSidebar()}"
    if old not in s: raise SystemExit('renderAll anchor missing')
    s = s.replace(old,new,1)
    old_open = "function openSearch(){const dlg=$('searchDialog');dlg.showModal();setTimeout(()=>$('searchInput').focus(),20);renderSearch('')}"
    new_open = "function openSearch(){const dlg=$('searchDialog');dlg.showModal();setTimeout(()=>$('searchInput').focus(),20);renderSearch('')}"
    if old_open not in s: raise SystemExit('openSearch anchor missing')
    # Add click handling without changing the existing openSearch implementation.
    click_anchor = "$('searchInput').oninput=e=>renderSearch(e.target.value);"
    click_code = "$('searchInput').oninput=e=>renderSearch(e.target.value);$('searchResults').onclick=e=>{const row=e.target.closest('[data-palette-view]');if(!row)return;$('searchDialog').close();showView(row.dataset.paletteView)};"
    if click_anchor not in s: raise SystemExit('search input handler anchor missing')
    s = s.replace(click_anchor, click_code, 1)
    s = s.replace('placeholder="Search projects, milestones, events…"', 'placeholder="Search everything or type > command…"', 1)

# Enforce Phase C contract on every run.
required = [marker, 'data-view="review"', 'id="view-review"', 'function renderWeeklyReview()', 'function analyticsData()', 'const paletteCommands=', 'data-palette-view']
missing = [x for x in required if x not in s]
if missing: raise SystemExit('Phase C UI contract missing: '+', '.join(missing))
s = s.replace("navigator.serviceWorker.register('./sw.js?v=phase-b-v1'", "navigator.serviceWorker.register('./sw.js?v=phase-c-v1'")
p.write_text(s, encoding='utf-8')

sw = Path('sw.js')
if sw.exists():
    x = sw.read_text(encoding='utf-8')
    x = re.sub(r"const CACHE_NAME = '[^']+';", "const CACHE_NAME = 'nextplan-shell-v12-phase-c';", x, count=1)
    sw.write_text(x, encoding='utf-8')

print('Phase C UI contract verified: Weekly Review, knowledge integration, unified search/commands and analytics v1.')
