from pathlib import Path

p = Path('index.html')
s = p.read_text(encoding='utf-8')

s = s.replace(
    '<dialog class="modal" id="nextDialog"><div class="modal-inner"><div class="modal-title">Your Next Plan</div><div class="modal-sub">只从当前可行动项目中选择，Waiting 会自动排除。</div><div id="nextDialogBody"></div><div class="modal-actions"><button class="primary" id="closeNext">Got it</button></div></div></dialog>',
    '<dialog class="modal" id="nextDialog"><div class="modal-inner"><div class="modal-title">Do this now</div><div class="modal-sub">NextPlan 根据重要性、时间、准备窗口与可执行性动态推荐一个当前动作。</div><div id="nextDialogBody"></div><div class="modal-actions"><button class="secondary" id="pickAlternative">Pick something else</button><span style="flex:1"></span><button class="primary" id="closeNext">Got it</button></div></div></dialog>'
)
s = s.replace('projects:[],events:[],notes:[],resources:[],deadlines:[]', 'projects:[],events:[],notes:[],resources:[],deadlines:[],calendar_events:[]')
s = s.replace('let state=loadCache(),busy=false,syncTimer=null,currentView=\'home\',calendarCursor=new Date(),miniCursor=new Date();', "let state=loadCache(),busy=false,syncTimer=null,currentView='home',calendarCursor=new Date(),miniCursor=new Date(),lastPickKey=null;")

calendar_helpers = r'''function parseLocalDate(raw){if(!raw)return null;const m=String(raw).match(/^(\d{4})-(\d{2})-(\d{2})$/);if(m)return new Date(Number(m[1]),Number(m[2])-1,Number(m[3]));const d=new Date(raw);return Number.isNaN(d.getTime())?null:d}
function confirmedDeadlines(){const out=[];const add=(raw,base={})=>{const date=parseLocalDate(raw);if(!date)return;out.push({...base,date,raw})};(state.deadlines||[]).forEach(d=>{if(['event','meeting','appointment','presentation','reminder'].includes(String(d.kind||'')))return;add(d.date||d.due,{id:d.id,title:d.title||d.name||'Deadline',category:d.category||'',project_id:d.project_id,task_id:d.task_id,time:d.time||'',timezone:d.timezone||'',kind:'deadline',prep_days:d.prep_days})});(state.projects||[]).forEach(p=>{add(p.deadline||p.due,{id:'project-due-'+p.id,title:p.name,category:p.category,project_id:p.id,kind:'deadline',prep_days:p.prep_days});(p.milestones||[]).forEach(m=>add(m.deadline||m.due,{id:'task-due-'+p.id+'-'+m.id,title:m.name,category:p.category,project_id:p.id,task_id:m.id,kind:'deadline',prep_days:m.prep_days}))});const seen=new Set();return out.filter(x=>{const k=(x.id||'')+'|'+x.title+'|'+localISO(x.date);if(seen.has(k))return false;seen.add(k);return true}).sort((a,b)=>a.date-b.date||String(a.time||'').localeCompare(String(b.time||'')))}
function calendarEntries(){const out=confirmedDeadlines().map(x=>({...x,type:'deadline'}));const addEvent=e=>{const date=parseLocalDate(e.date||e.due);if(!date)return;out.push({id:e.id,title:e.title||e.name||'Event',date,time:e.time||'',timezone:e.timezone||'',kind:e.kind||'event',type:'calendar_event',category:e.category||'',project_id:e.project_id,task_id:e.task_id,prep_days:e.prep_days})};(state.calendar_events||[]).forEach(addEvent);(state.deadlines||[]).filter(d=>['event','meeting','appointment','presentation','reminder'].includes(String(d.kind||''))).forEach(addEvent);const seen=new Set();return out.filter(x=>{const k=(x.id||'')+'|'+x.title+'|'+localISO(x.date)+'|'+(x.time||'');if(seen.has(k))return false;seen.add(k);return true}).sort((a,b)=>a.date-b.date||String(a.time||'').localeCompare(String(b.time||'')))}'''

decision_helpers = r'''function deadlineUrgency(days){if(days==null)return 0;if(days<=0)return 55;if(days===1)return 50;if(days===2)return 44;if(days===3)return 36;if(days<=7)return Math.max(12,30-(days-4)*4.5);if(days<=14)return Math.max(2,10-(days-8)*1.2);return 0}
function preparationBonus(days,prep){if(days==null||prep<=0||days<0||days>prep)return 0;return 10+16*((prep-days)/Math.max(1,prep))}
function activityBonuses(raw){if(!raw)return{continuity:0,neglect:0};const d=new Date(raw);if(Number.isNaN(d.getTime()))return{continuity:0,neglect:0};const age=Math.max(0,(Date.now()-d.getTime())/86400000);return{continuity:age<=1?8:age<=3?4:0,neglect:age<7?0:Math.min(12,2+(age-7)*.8)}}
function decisionSchedule(p,m){const list=[];confirmedDeadlines().forEach(d=>{if(m&&d.task_id&&String(d.task_id)===String(m.id))list.push(d);else if(d.project_id&&String(d.project_id)===String(p.id))list.push(d)});(state.calendar_events||[]).forEach(e=>{if(String(e.project_id||'')!==String(p.id)||!['presentation','meeting'].includes(String(e.kind||'')))return;const date=parseLocalDate(e.date);if(date)list.push({...e,date,type:'calendar_event'})});return list.sort((a,b)=>a.date-b.date)}
function decisionCandidates(){const out=[];(state.projects||[]).filter(p=>p.status==='active').forEach(p=>{const active=(p.milestones||[]).filter(m=>m.status==='active');const work=active.length?active:(p.next_action?[null]:[]);work.forEach(m=>{const pr=Math.max(1,Math.min(3,Number(p.priority)||1)),priority={1:20,2:35,3:50}[pr],sched=decisionSchedule(p,m),nearest=sched[0]||null,days=nearest?daysDiff(nearest.date):null,urgency=deadlineUrgency(days);let prep=m?.prep_days??p.prep_days??nearest?.prep_days;if(prep==null)prep=nearest?.kind==='presentation'?5:nearest?.type==='calendar_event'?1:3;prep=Math.max(0,Number(prep)||0);const preparation=preparationBonus(days,prep),ab=activityBonuses(m?.last_worked_at||p.last_worked_at),score=priority+urgency+preparation+ab.continuity+ab.neglect,reasons=[(pr===3?'High':pr===2?'Medium':'Low')+' priority'];if(days!=null){reasons.push(days<=0?'deadline is due or overdue':`deadline in ${days} day${days===1?'':'s'}`);if(preparation>0)reasons.push('preparation window active')}if(ab.continuity>0)reasons.push('continuity bonus');if(ab.neglect>0)reasons.push('long-term item has been neglected');out.push({key:p.id+'::'+(m?.id||'project'),project:p,name:m?.name||p.next_action||p.name,desc:p.next_action||'',priority:p.priority,score,deadlineDays:days,why:reasons.join(' · ')})})});return out.sort((a,b)=>b.score-a.score||String(a.project.name).localeCompare(String(b.project.name)))}
function chooseDecision(excludeKey=null){const pool=decisionCandidates().filter(x=>x.key!==excludeKey);if(!pool.length)return null;const top=pool[0],second=pool[1],det=(top.deadlineDays!=null&&top.deadlineDays<=2)||!second||top.score-second.score>=15;if(det)return{...top,mode:'deterministic',poolCount:pool.length};const near=pool.filter(x=>top.score-x.score<=12).slice(0,5),weights=near.map(x=>Math.exp((x.score-top.score)/6)),sum=weights.reduce((a,b)=>a+b,0);let r=Math.random()*sum;for(let i=0;i<near.length;i++){r-=weights[i];if(r<=0)return{...near[i],mode:'weighted-near-top',poolCount:pool.length}}return{...top,mode:'weighted-near-top',poolCount:pool.length}}
function actionableTasks(){return decisionCandidates()}'''

new_render_calendar = r'''function renderCalendar(cursor,gridId,titleId,mini=false){const y=cursor.getFullYear(),m=cursor.getMonth();if(titleId)$(titleId).textContent=new Intl.DateTimeFormat('en-AU',{month:'long',year:'numeric'}).format(cursor);const first=new Date(y,m,1),offset=(first.getDay()+6)%7,days=new Date(y,m+1,0).getDate(),prevDays=new Date(y,m,0).getDate(),entries=calendarEntries();let html='';for(let i=0;i<42;i++){let n,dm=m,dy=y,muted=false;if(i<offset){n=prevDays-offset+i+1;dm=m-1;muted=true}else if(i>=offset+days){n=i-(offset+days)+1;dm=m+1;muted=true}else n=i-offset+1;const date=new Date(dy,dm,n),iso=localISO(date),events=entries.filter(d=>localISO(d.date)===iso),today=localISO(new Date())===iso,title=events.map(e=>(e.time?e.time+' ':'')+e.title).join(', ');if(mini)html+=`<div class="mini-day ${muted?'muted ':''}${today?'today ':''}${events.length?'has-event':''}" title="${esc(title)}">${n}</div>`;else html+=`<div class="day ${muted?'muted ':''}${today?'today ':''}${events.length?'has-event':''}"><div class="daynum">${n}</div>${events.length?`<div style="font-size:9px;color:var(--muted);margin-top:5px;line-height:1.2">${esc((events[0].time?events[0].time+' ':'')+events[0].title)}</div><div class="event-dots">${events.slice(0,3).map(e=>`<span style="background:${deadlineColor(e.category)}"></span>`).join('')}</div>`:''}</div>`}$(gridId).innerHTML=html}'''

new_render_upcoming = r'''function renderUpcoming(){const now=startOfToday(),all=calendarEntries().filter(x=>x.date>=now);const renderItem=(x,side=false)=>{const dd=daysDiff(x.date),right=dd===0?'Today':dd===1?'1 day':dd+' days',date=x.date.toLocaleDateString('en-AU',{weekday:'short',day:'numeric',month:'short',year:'numeric'})+(x.time?' · '+x.time:''),col=deadlineColor(x.category),kind=x.type==='deadline'?'Deadline':(x.kind||'Event');return side?`<div class="side-event"><span class="u-dot" style="background:${col}"></span><div><div class="side-event-title">${esc(x.title)}</div><div class="side-event-date">${esc(kind)} · ${date}</div></div><div class="side-event-right">${right}</div></div>`:`<div class="upcoming-item"><span class="u-dot" style="background:${col}"></span><div><div class="u-title">${esc(x.title)}</div><div class="u-date">${esc(kind)} · ${date}</div></div><div class="u-right">${right}</div></div>`};$('calendarUpcoming').innerHTML=all.length?all.slice(0,10).map(x=>renderItem(x,false)).join(''):`<div class="empty-state"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7"><rect x="4" y="5" width="16" height="15" rx="2"/><path d="M8 3v4m8-4v4M4 10h16"/></svg><b>暂无日历事项</b>确认过的 meeting、presentation 与 deadline 会显示在这里。</div>`;$('sideUpcoming').innerHTML=all.length?all.slice(0,4).map(x=>renderItem(x,true)).join(''):`<div class="list-sub" style="padding:10px 0">No upcoming items.</div>`}'''

new_pick = r'''function pickNext(alternative=false){const exclude=alternative?lastPickKey:null,t=chooseDecision(exclude),dlg=$('nextDialog'),body=$('nextDialogBody'),alt=$('pickAlternative');if(!t){body.innerHTML=`<div class="empty-state"><b>现在没有必须推进的主动事项</b>Waiting / blocked 项目已经自动排除。</div>`;lastPickKey=null;alt.style.display='none'}else{lastPickKey=t.key;const p=t.project,pc=projectPct(p),deadline=t.deadlineDays==null?'':(t.deadlineDays<=0?' · Due now':` · ${t.deadlineDays}d remaining`);body.innerHTML=`<div class="card" style="padding:16px;box-shadow:none"><div class="pc-top"><div class="pc-icon" style="background:${colorForCategory(p.category)[0]};color:${colorForCategory(p.category)[1]}">${iconForCategory(p.category)}</div><div class="pc-text"><div class="pc-title" style="font-size:16px">${esc(t.name)}</div><div class="pc-sub">${esc(p.name)} · ${priorityLabel(p.priority)}${deadline}</div></div><div class="pc-pct">${Math.round(t.score)}</div></div><div class="next" style="margin-top:13px"><b>Why this?</b>${esc(t.why)}</div><div class="next" style="margin-top:9px"><b>Current action</b>${esc(p.next_action||t.name)}</div></div>`;alt.style.display=t.poolCount>1?'inline-flex':'none'}if(!dlg.open)dlg.showModal()}'''

lines=s.splitlines();out=[]
flags={"deadlines":False,"tasks":False,"calendar":False,"upcoming":False,"pick":False}
for line in lines:
    if line.startswith('function confirmedDeadlines(){'):
        out.extend(calendar_helpers.splitlines());flags['deadlines']=True
    elif line.startswith('function actionableTasks(){'):
        out.extend(decision_helpers.splitlines());flags['tasks']=True
    elif line.startswith('function renderCalendar('):
        out.append(new_render_calendar);flags['calendar']=True
    elif line.startswith('function renderUpcoming(){'):
        out.append(new_render_upcoming);flags['upcoming']=True
    elif line.startswith('function pickNext(){') or line.startswith('function pickNext('):
        out.append(new_pick);flags['pick']=True
    else:
        out.append(line)

missing=[k for k,v in flags.items() if not v]
if missing: raise SystemExit('Phase B patch anchors missing: '+', '.join(missing))
s='\n'.join(out)+'\n'
s=s.replace("$('nextActionBtn').onclick=pickNext;$('closeNext').onclick=()=>$('nextDialog').close();", "$('nextActionBtn').onclick=()=>pickNext(false);$('pickAlternative').onclick=()=>pickNext(true);$('closeNext').onclick=()=>$('nextDialog').close();")
s=s.replace("navigator.serviceWorker.register('./sw.js?v=home-all-projects-v1',{updateViaCache:'none'})", "navigator.serviceWorker.register('./sw.js?v=phase-b-v1',{updateViaCache:'none'})")
p.write_text(s,encoding='utf-8')

Path('sw.js').write_text("""const CACHE_NAME = 'nextplan-shell-v11-phase-b';
const APP_SHELL = ['./', './index.html', './manifest.webmanifest', './icon.svg'];
self.addEventListener('install', event => { event.waitUntil(caches.open(CACHE_NAME).then(cache => cache.addAll(APP_SHELL))); self.skipWaiting(); });
self.addEventListener('activate', event => { event.waitUntil(caches.keys().then(keys => Promise.all(keys.filter(k => k !== CACHE_NAME).map(k => caches.delete(k))))); self.clients.claim(); });
self.addEventListener('fetch', event => { const request=event.request;if(request.method!=='GET')return;if(request.mode==='navigate'){event.respondWith(fetch(request,{cache:'no-store'}).then(response=>{const copy=response.clone();caches.open(CACHE_NAME).then(cache=>cache.put('./index.html',copy));return response}).catch(()=>caches.match('./index.html')));return}const url=new URL(request.url);if(url.origin===self.location.origin){event.respondWith(fetch(request,{cache:'no-store'}).then(response=>{const copy=response.clone();caches.open(CACHE_NAME).then(cache=>cache.put(request,copy));return response}).catch(()=>caches.match(request)))}});
""",encoding='utf-8')
print('Applied NextPlan Phase B UI: workflow-aware tasks, Decision Engine v1, Calendar + Deadline v1.')
