const DEFAULTS={endpoint:"http://127.0.0.1:47123",bridgeEndpoint:"http://127.0.0.1:47124",token:"",autoSync:true,autoThreshold:0.88};
const GENERATION="local-v0.1.4-windows-final";
const CAL_COMPAT_PREFIX="__NP_CAL_V1__:";
const NOTE_COMPAT_PREFIX="__NP_NOTE_V1__:";
const RESOURCE_COMPAT_PREFIX="__NP_RESOURCE_V1__:";
const AUTOMATION_COMPAT_PREFIX="__NP_AUT_V1__:";

async function getConfig(){return{...DEFAULTS,...(await chrome.storage.local.get(DEFAULTS))}}
async function readJson(r){try{return await r.json()}catch{return{}}}
async function bootstrapSession(){
  const c=await getConfig();let r;
  try{r=await fetch(`${c.bridgeEndpoint}/bridge/bootstrap`,{method:"POST",cache:"no-store",headers:{"Content-Type":"application/json","X-NextPlan-Extension-Id":chrome.runtime.id},body:"{}"})}
  catch{throw new Error("Open NextPlan Desktop to connect")}
  const b=await readJson(r);
  if(!r.ok){if(r.status===403)throw new Error("This is not the official NextPlan Local Bridge build");if(r.status===503)throw new Error("NextPlan Desktop is starting. Try again in a moment.");throw new Error(b.error||`Desktop bridge HTTP ${r.status}`)}
  if(!b.token||!b.endpoint)throw new Error("Desktop bridge returned an incomplete session");
  const endpoint=String(b.endpoint).replace(/\/$/,"");
  await chrome.storage.local.set({token:b.token,endpoint,lastBootstrap:new Date().toISOString()});
  return{...c,token:b.token,endpoint};
}
async function api(path,o={},auth=true,retry=true){
  let c=await getConfig();if(auth&&!c.token)c=await bootstrapSession();
  const headers={"Content-Type":"application/json",...(o.headers||{})};if(auth)headers.Authorization=`Bearer ${c.token}`;
  let r;try{r=await fetch(`${c.endpoint}${path}`,{...o,headers,cache:"no-store"})}catch{if(auth&&retry){await chrome.storage.local.set({token:""});await bootstrapSession();return api(path,o,auth,false)}throw new Error("NextPlan Desktop is not reachable")}
  const b=await readJson(r);
  if((r.status===401||r.status===403)&&auth&&retry){await chrome.storage.local.set({token:""});await bootstrapSession();return api(path,o,auth,false)}
  if(!r.ok)throw new Error(b.detail||b.error||`HTTP ${r.status}`);return b;
}
async function getPending(){return(await api("/pending")).pending||[]}
async function refreshBadge(){let x=[];try{x=await getPending()}catch{}await chrome.action.setBadgeText({text:x.length?String(Math.min(x.length,99)):""});await chrome.action.setBadgeBackgroundColor({color:"#3478F6"});return x}
async function connectDesktop(){const c=await getConfig();if(!c.token)await bootstrapSession();await api("/state");const h=await api("/healthz",{},false);await refreshBadge();const n=await getConfig();return{status:"connected",endpoint:n.endpoint,runtime:h.runtime||"nextplan-local-core"}}

async function seen(fp){const{processedFingerprints=[]}=await chrome.storage.local.get({processedFingerprints:[]});return processedFingerprints.includes(`${GENERATION}:${fp}`)}
async function remember(fp){const{processedFingerprints=[]}=await chrome.storage.local.get({processedFingerprints:[]}),k=`${GENERATION}:${fp}`;if(!processedFingerprints.includes(k))await chrome.storage.local.set({processedFingerprints:[...processedFingerprints,k].slice(-300)})}
function clientContext(){let timezone="";try{timezone=Intl.DateTimeFormat().resolvedOptions().timeZone||""}catch{}return{source:"nextplan-local-extension",bridgeVersion:"0.1.4",now:new Date().toISOString(),timezone,utcOffsetMinutes:-new Date().getTimezoneOffset()}}

function normalizeCommandText(t){return String(t||"").replace(/next\s*plan\s*[：:]\s*/gi,"NextPlan ").replace(/((?:新增|新建|创建|添加)\s*(?:一个)?\s*(?:新)?项目)(?=[^\s：:，。])/gi,"$1 ").trim()}
function cleanName(v){return String(v||"").trim().replace(/^[\s“”"'「」『』【】]+|[\s“”"'「」『』【】]+$/g,"").replace(/\s*项目$/i,"").trim()}
function nameKey(v){return cleanName(v).replace(/\s+/g,"").toLocaleLowerCase()}
function statusValue(r){const s=String(r||"").trim().toLocaleLowerCase();if(["active","进行中","正在进行","已开始"].includes(s))return"active";if(["waiting","等待","待定"].includes(s))return"waiting";if(["planned","计划中","未开始","尚未开始"].includes(s))return"planned";if(["completed","done","已完成","完成"].includes(s))return"completed";if(["blocked","阻塞","暂停"].includes(s))return"blocked";return""}
function hashKey(v){let h=2166136261;for(const ch of String(v||"")){h^=ch.codePointAt(0);h=Math.imul(h,16777619)}return(h>>>0).toString(36)}
function todayISO(){return localDateISO(new Date())}
function compatTitle(prefix,obj){return prefix+encodeURIComponent(JSON.stringify(obj))}
function decodeCompatTitle(raw,prefix){if(!String(raw||"").startsWith(prefix))return null;try{return JSON.parse(decodeURIComponent(String(raw).slice(prefix.length)))}catch{return null}}
function isUnsupportedAction(err,action){const m=String(err?.message||"");return new RegExp(`unsupported local action|unsupported.*${action}`,"i").test(m)}
async function executeAction(action){return api("/actions/execute",{method:"POST",body:JSON.stringify({action})})}
async function rawState(){return api("/state")}
function exactProjectFromText(state,text){const hay=nameKey(text);return(state.projects||[]).filter(p=>p?.name).sort((a,b)=>String(b.name).length-String(a.name).length).find(p=>hay.includes(nameKey(p.name)))||null}

function parseProjectStatusCommand(t){
  const s=normalizeCommandText(t).replace(/^NextPlan\s*/i,"").trim();
  if(/(?:任务|task|milestone|步骤)/i.test(s))return null;
  const m=s.match(/(?:把|将)\s*[“"「『]?([^”"」』，。]+?)[”"」』]?\s*(?:项目)?\s*(?:设置为|设为|改成|改为|标记为|设置成)\s*(active|waiting|planned|completed|done|blocked|进行中|正在进行|已开始|等待|待定|计划中|未开始|尚未开始|已完成|完成|阻塞|暂停)/i);
  if(!m)return null;const name=cleanName(m[1]),status=statusValue(m[2]);return name&&status?{name,status}:null;
}

function localDateISO(d){return`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`}
function parseCalendarDate(t){
  const n=new Date();let m=t.match(/(20\d{2})年(\d{1,2})月(\d{1,2})日/);if(m){const d=new Date(+m[1],+m[2]-1,+m[3]);return Number.isNaN(d.getTime())?"":localDateISO(d)}
  m=t.match(/\b(20\d{2})-(\d{1,2})-(\d{1,2})\b/);if(m){const d=new Date(+m[1],+m[2]-1,+m[3]);return Number.isNaN(d.getTime())?"":localDateISO(d)}
  m=t.match(/(?<!\d)(\d{1,2})月(\d{1,2})日/);if(m){let d=new Date(n.getFullYear(),+m[1]-1,+m[2]);if(d.getTime()<new Date(n.getFullYear(),n.getMonth(),n.getDate()).getTime()-86400000)d=new Date(n.getFullYear()+1,+m[1]-1,+m[2]);return Number.isNaN(d.getTime())?"":localDateISO(d)}
  const d=new Date(n.getFullYear(),n.getMonth(),n.getDate());if(t.includes("后天"))d.setDate(d.getDate()+2);else if(t.includes("明天"))d.setDate(d.getDate()+1);else if(!t.includes("今天"))return"";return localDateISO(d);
}
function parseCalendarTime(t){let m=t.match(/\b([01]?\d|2[0-3]):([0-5]\d)\s*(am|pm)?\b/i);if(m){let h=+m[1];const min=+m[2],ap=String(m[3]||"").toLowerCase();if(ap==="pm"&&h<12)h+=12;if(ap==="am"&&h===12)h=0;return`${String(h).padStart(2,"0")}:${String(min).padStart(2,"0")}`}m=t.match(/(上午|早上|中午|下午|晚上|傍晚)?\s*(\d{1,2})点(半|([0-5]?\d)分?)?/);if(!m)return"";const p=m[1]||"";let h=+m[2];const min=m[3]==="半"?30:+(m[4]||0);if(["下午","晚上","傍晚"].includes(p)&&h<12)h+=12;else if(p==="中午"&&h>=1&&h<11)h+=12;else if(["上午","早上"].includes(p)&&h===12)h=0;return h<=23&&min<=59?`${String(h).padStart(2,"0")}:${String(min).padStart(2,"0")}`:""}
function parseDeadlineCommand(t){const s=normalizeCommandText(t);if(!/(deadline|截止|到期|due\s*date)/i.test(s)||!/(next\s*plan|记录|记一下|加入|添加|写入|设置|设定)/i.test(s))return null;const date=parseCalendarDate(s);if(!date)return null;const time=parseCalendarTime(s);let title="Deadline";const q=s.match(/[“"「『]([^”"」』]+)[”"」』]/);if(q&&q[1]&&!/(next\s*plan)/i.test(q[1]))title=cleanName(q[1]);return{title:title||"Deadline",date,time,timezone:clientContext().timezone||""}}
function parseCalendarCommand(t){const s=normalizeCommandText(t);if(/(deadline|截止|到期|due\s*date)/i.test(s))return null;if(!/(next\s*plan|记录|记一下|日历|calendar|加入|添加)/i.test(s)||!/(meeting|会议|约会|appointment|presentation|提醒|reminder)/i.test(s))return null;const date=parseCalendarDate(s);if(!date)return null;const time=parseCalendarTime(s);let title="Meeting";const a=s.match(/有(?:一个|个)?\s*[“"「『]?([^”"」』，。]+?)[”"」』]?\s*(?:[。！!]|$)/i);if(a)title=cleanName(a[1]);else if(/导师/.test(s)&&/meeting|会议|见面/i.test(s))title="与导师 Meeting";else if(/presentation|汇报/i.test(s))title="Presentation";else if(/提醒|reminder/i.test(s))title="Reminder";const kind=/presentation|汇报/i.test(s)?"presentation":/提醒|reminder/i.test(s)?"reminder":/appointment|约会/i.test(s)?"appointment":"meeting";return{title:title||"Meeting",date,time,kind,timezone:clientContext().timezone||"",category:"其他"}}
function cleanCompatTitle(text,fallback){let s=String(text||"").replace(/https?:\/\/\S+/gi,"").replace(/^\s*NextPlan\s*/i,"").replace(/^(帮我|请|麻烦)?\s*(记录|记一下|记下来|保存|添加|加入|写入|存一下)\s*/i,"").replace(/(为|成|作为)?\s*(一条)?\s*(笔记|note|资源|resource)\s*/ig,"").replace(/(?:标题|title)\s*[:：]\s*[^,，。\n]+/ig,"").trim().replace(/^[：:，,。.!！\s]+|[：:，,。.!！\s]+$/g,"");return(s||fallback).slice(0,42)}
function parseNoteCommand(t){const s=normalizeCommandText(t);const del=/(删除|移除|去掉|删掉)\s*(?:一条)?\s*(?:笔记|note)/i.test(s);const add=/(记下来|记个笔记|记一条笔记|保存为笔记|作为笔记|加入笔记|添加笔记|save\s+(?:this\s+)?(?:as\s+)?note|note\s+this)/i.test(s);if(!del&&!add||/[?？]\s*$/.test(s))return null;const tm=s.match(/(?:标题|title)\s*[:：]\s*([^\n,，。]+)/i)||s.match(/(?:删除|移除|去掉|删掉)\s*(?:一条)?\s*(?:笔记|note)\s*[“"「『]?([^”"」』，。\n]+)/i);const title=cleanName(tm?.[1]||cleanCompatTitle(s,"对话笔记"));if(!title)return null;return{mode:del?"delete":"upsert",title,body:s}}
function parseResourceCommand(t){const s=normalizeCommandText(t);const del=/(删除|移除|去掉|删掉)\s*(?:一条)?\s*(?:资源|resource)/i.test(s);const add=/(保存为资源|作为资源|加入资源|添加资源|资源索引|save\s+(?:this\s+)?(?:as\s+)?resource|add\s+(?:this\s+)?resource)/i.test(s);if(!del&&!add||/[?？]\s*$/.test(s))return null;const um=s.match(/https?:\/\/[^\s<>\]\)）]+/i);const tm=s.match(/(?:标题|title)\s*[:：]\s*([^\n,，。]+)/i)||s.match(/(?:删除|移除|去掉|删掉)\s*(?:一条)?\s*(?:资源|resource)\s*[“"「『]?([^”"」』，。\n]+)/i);const location=um?um[0].replace(/[.,，。]+$/g,""):"";const title=cleanName(tm?.[1]||cleanCompatTitle(s,"资源"));if(add&&!location)return null;if(!title&&!location)return null;return{mode:del?"delete":"upsert",title:title||"资源",location,description:s}}
const RULE_PATTERNS=[["overdue-deadline",/逾期|overdue/i],["preparation-window",/准备窗口|准备提醒|preparation/i],["stale-active",/停滞|长期没动|stale/i],["waiting-followup",/等待.*(?:提醒|follow)|waiting.*follow/i],["blocked-project",/阻塞|blocked/i],["missing-next-action",/没有.*下一步|missing.*next/i],["weekly-review",/每周复盘|weekly\s*review/i]];
function parseAutomationCommand(t){const s=normalizeCommandText(t);if(!/(自动|automation|规则|提醒)/i.test(s))return null;const hit=RULE_PATTERNS.find(([,re])=>re.test(s));if(!hit)return null;const rule_id=hit[0],disable=/(关闭|禁用|停用|不要|disable|turn\s+off)/i.test(s),enable=/(开启|启用|打开|enable|turn\s+on)/i.test(s),dm=s.match(/(\d{1,3})\s*(?:天|days?)/i);if(!disable&&!enable&&!dm)return null;const out={rule_id};if(disable||enable)out.enabled=!disable;if(dm&&["preparation-window","stale-active","waiting-followup"].includes(rule_id))out.threshold_days=Math.max(1,Math.min(365,+dm[1]));return out}

function compatCalendarTitle(e){return compatTitle(CAL_COMPAT_PREFIX,{title:e.title,time:e.time||"",timezone:e.timezone||"",kind:e.kind||"event",category:e.category||"其他"})}
async function directProjectStatus(t){const p=parseProjectStatusCommand(t);if(!p)return null;const s=await rawState(),project=(s.projects||[]).find(x=>nameKey(x.name)===nameKey(p.name));if(!project)return{status:"error",error:`Project not found: ${p.name}`};if(String(project.status||"")===p.status)return{status:"informational",label:`项目状态已是 ${p.status}：${project.name}`};const receipt=await executeAction({action:"update_project",project_id:project.id,status:p.status});return{status:"auto_synced",label:`更新项目状态：${project.name} → ${p.status}`,receipt}}
async function directDeadlineWrite(t){const e=parseDeadlineCommand(t);if(!e)return null;const s=await rawState();const project=exactProjectFromText(s,t);const title=project?`${project.name} Deadline`:e.title;const receipt=await executeAction({action:"set_deadline",project_id:project?.id||"",title,date:e.date,time:e.time||"",timezone:e.timezone||""});return{status:"auto_synced",label:`记录截止日期：${title} · ${e.date}${e.time?` ${e.time}`:""}`,receipt}}
async function directCalendarWrite(t){const e=parseCalendarCommand(t);if(!e)return null;try{const receipt=await executeAction({action:"upsert_calendar_event",...e});return{status:"auto_synced",label:`记录日历：${e.title} · ${e.date}${e.time?` ${e.time}`:""}`,receipt}}catch(err){if(!isUnsupportedAction(err,"upsert_calendar_event"))throw err}const receipt=await executeAction({action:"set_deadline",project_id:"calendar",deadline_id:`compat-calendar-${hashKey(`${e.title}|${e.date}|${e.time}|${e.kind}`)}`,title:compatCalendarTitle(e),date:e.date});return{status:"auto_synced",label:`记录日历：${e.title} · ${e.date}${e.time?` ${e.time}`:""}`,receipt,compatibility:"calendar-event-v1"}}
async function directNoteWrite(t){const n=parseNoteCommand(t);if(!n)return null;const s=await rawState();const project=exactProjectFromText(s,t),pid=project?.id||"";const id=`note-${hashKey(`${pid}|${n.title}`)}`;if(n.mode==="delete"){const meta={id,title:n.title,project_id:pid||null,deleted:true,updated_at:new Date().toISOString()};const receipt=await executeAction({action:"set_deadline",project_id:pid||"notes",deadline_id:`compat-${id}`,title:compatTitle(NOTE_COMPAT_PREFIX,meta),date:todayISO()});return{status:"auto_synced",label:`删除笔记：${n.title}`,receipt,compatibility:"note-v1"}}try{const receipt=await executeAction({action:"add_note",note_id:id,title:n.title,body:n.body,category:project?.category||"Note",project_id:pid});return{status:"auto_synced",label:`保存笔记：${n.title}`,receipt}}catch(err){if(!isUnsupportedAction(err,"add_note"))throw err}const meta={id,title:n.title,body:n.body,category:project?.category||"Note",project_id:pid||null,tags:[],updated_at:new Date().toISOString()};const receipt=await executeAction({action:"set_deadline",project_id:pid||"notes",deadline_id:`compat-${id}`,title:compatTitle(NOTE_COMPAT_PREFIX,meta),date:todayISO()});return{status:"auto_synced",label:`保存笔记：${n.title}`,receipt,compatibility:"note-v1"}}
async function directResourceWrite(t){const r=parseResourceCommand(t);if(!r)return null;const s=await rawState();const project=exactProjectFromText(s,t),pid=project?.id||"";let key=r.location||r.title,id=`resource-${hashKey(`${pid}|${key}`)}`;if(r.mode==="delete"&&!r.location){for(const d of(s.deadlines||[])){const meta=decodeCompatTitle(d.title,RESOURCE_COMPAT_PREFIX);if(meta&&!meta.deleted&&nameKey(meta.title)===nameKey(r.title)){id=meta.id||id;break}}const meta={id,title:r.title,project_id:pid||null,deleted:true,updated_at:new Date().toISOString()};const receipt=await executeAction({action:"set_deadline",project_id:pid||"resources",deadline_id:`compat-${id}`,title:compatTitle(RESOURCE_COMPAT_PREFIX,meta),date:todayISO()});return{status:"auto_synced",label:`删除资源：${r.title}`,receipt,compatibility:"resource-v1"}}if(r.mode==="delete"){const meta={id,title:r.title,location:r.location,project_id:pid||null,deleted:true,updated_at:new Date().toISOString()};const receipt=await executeAction({action:"set_deadline",project_id:pid||"resources",deadline_id:`compat-${id}`,title:compatTitle(RESOURCE_COMPAT_PREFIX,meta),date:todayISO()});return{status:"auto_synced",label:`删除资源：${r.title}`,receipt,compatibility:"resource-v1"}}try{const receipt=await executeAction({action:"add_resource",resource_id:id,title:r.title,location:r.location,description:r.description,resource_type:"link",project_id:pid});return{status:"auto_synced",label:`保存资源：${r.title}`,receipt}}catch(err){if(!isUnsupportedAction(err,"add_resource"))throw err}const meta={id,title:r.title,location:r.location,type:"link",description:r.description,project_id:pid||null,tags:[],updated_at:new Date().toISOString()};const receipt=await executeAction({action:"set_deadline",project_id:pid||"resources",deadline_id:`compat-${id}`,title:compatTitle(RESOURCE_COMPAT_PREFIX,meta),date:todayISO()});return{status:"auto_synced",label:`保存资源：${r.title}`,receipt,compatibility:"resource-v1"}}
async function directAutomationWrite(t){const a=parseAutomationCommand(t);if(!a)return null;try{const receipt=await executeAction({action:"upsert_automation_rule",...a});return{status:"auto_synced",label:`更新自动化规则：${a.rule_id}`,receipt}}catch(err){if(!isUnsupportedAction(err,"upsert_automation_rule"))throw err}const id=`automation-${a.rule_id}`,meta={id:a.rule_id,enabled:a.enabled!==undefined?a.enabled:true,...(a.threshold_days?{threshold_days:a.threshold_days}:{}),updated_at:new Date().toISOString()};const receipt=await executeAction({action:"set_deadline",project_id:"automation",deadline_id:`compat-${id}`,title:compatTitle(AUTOMATION_COMPAT_PREFIX,meta),date:todayISO()});return{status:"auto_synced",label:`更新自动化规则：${a.rule_id}`,receipt,compatibility:"automation-rule-v1"}}

async function recordDirectResult(fp,r){if(!r)return null;if(r.status==="error")return r;if(r.status==="auto_synced")await chrome.storage.local.set({lastSync:{at:new Date().toISOString(),label:r.label,result:r.receipt?.status||"applied"}});await remember(fp);return r}
async function handleTurn(turn){
  if(await seen(turn.fingerprint))return{status:"duplicate"};
  const nt={...turn,userText:normalizeCommandText(turn.userText)};
  try{
    for(const direct of [directProjectStatus,directDeadlineWrite,directCalendarWrite,directNoteWrite,directResourceWrite,directAutomationWrite]){const r=await direct(nt.userText);if(r)return await recordDirectResult(turn.fingerprint,r)}
  }catch(err){const m=String(err?.message||"Connection failed");return{status:m.includes("Open NextPlan Desktop")||m.includes("not reachable")?"needs_desktop":"error",error:m}}
  let r;try{r=await api("/conversation/capture",{method:"POST",body:JSON.stringify({turn:nt,client:clientContext(),apply:true})})}catch(err){const m=String(err?.message||"Connection failed");return{status:m.includes("Open NextPlan Desktop")||m.includes("not reachable")?"needs_desktop":"error",error:m}}
  const c=r?.candidate||null;if(!c){await remember(turn.fingerprint);return{status:"no_change"}}
  if(c.informational||!c.action){await remember(turn.fingerprint);return{status:"informational",label:c.label||"No change needed"}}
  if(r.receipt){await remember(turn.fingerprint);await chrome.storage.local.set({lastSync:{at:new Date().toISOString(),label:c.label,result:r.receipt.status}});return{status:"auto_synced",label:c.label,receipt:r.receipt}}
  await refreshBadge();await remember(turn.fingerprint);return{status:"queued",label:c.label,confidence:c.confidence,requiresConfirmation:Boolean(c.requiresConfirmation),kind:c.kind};
}
async function applyPending(id){const r=await api("/pending/apply",{method:"POST",body:JSON.stringify({id})});await refreshBadge();await chrome.storage.local.set({lastSync:{at:new Date().toISOString(),label:r.summary||id,result:r.status}});return r}
async function ignorePending(id){const r=await api("/pending/ignore",{method:"POST",body:JSON.stringify({id})});await refreshBadge();return r}
async function statusSnapshot(){let connectionError=null,runtime=null;try{const c=await connectDesktop();runtime=c.runtime}catch(e){connectionError=e.message}const config=await getConfig();let pending=[];if(!connectionError)try{pending=await getPending()}catch(e){connectionError=e.message}const{lastSync=null}=await chrome.storage.local.get({lastSync:null});return{connected:!connectionError,paired:!connectionError,connectionError,runtime,endpoint:config.endpoint,pending,lastSync,mode:"desktop-auto-bootstrap",version:"0.1.4"}}

chrome.runtime.onInstalled.addListener(async()=>{const c=await chrome.storage.local.get(Object.keys(DEFAULTS));await chrome.storage.local.set({...DEFAULTS,...c,token:""});try{await connectDesktop()}catch{}});
chrome.runtime.onStartup.addListener(async()=>{await chrome.storage.local.set({token:""});try{await connectDesktop()}catch{}});
chrome.runtime.onMessage.addListener((m,_s,send)=>{if(m?.type==="NEXTPLAN_TURN"){handleTurn(m.turn).then(send).catch(e=>send({status:"error",error:e.message}));return true}if(m?.type==="NEXTPLAN_CONNECT"||m?.type==="NEXTPLAN_PAIR"){connectDesktop().then(send).catch(e=>send({status:"error",error:e.message}));return true}if(m?.type==="NEXTPLAN_GET_STATUS"){statusSnapshot().then(send).catch(e=>send({connected:false,paired:false,connectionError:e.message,pending:[]}));return true}if(m?.type==="NEXTPLAN_APPLY"){applyPending(m.id).then(send).catch(e=>send({status:"error",error:e.message}));return true}if(m?.type==="NEXTPLAN_IGNORE"){ignorePending(m.id).then(send).catch(e=>send({status:"error",error:e.message}));return true}if(m?.type==="NEXTPLAN_TEST"){connectDesktop().then(send).catch(e=>send({status:"error",error:e.message}));return true}});
